In [1]:
import cv2
import os
data_path='dataset'
categories=os.listdir(data_path)  
labels=[i for i in range(len(categories))]

label_dict=dict(zip(categories,labels))  

print(label_dict)
print(categories)
print(labels)

{'anger': 0, 'contempt': 1, 'disgust': 2, 'fear': 3, 'happy': 4, 'sadness': 5, 'surprise': 6}
['anger', 'contempt', 'disgust', 'fear', 'happy', 'sadness', 'surprise']
[0, 1, 2, 3, 4, 5, 6]


In [2]:
img_size=100
data=[]
target=[]

for category in categories:
    folder_path=os.path.join(data_path,category)
    img_names=os.listdir(folder_path)
    
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)
        img=cv2.imread(img_path)
        
        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            #converting the image into grayscale
            
            resized=cv2.resize(gray,(img_size,img_size))
            #resizing the grayscale into 100x100 ,since we need a fixed common size for all images
            
            data.append(resized)
            target.append(label_dict[category])
            
            
        except Exception as e:
            print('Exception:',e)
            #if any exception raised ,the exception will be printed here.and pass to the next image

In [3]:
import numpy as np

data=np.array(data)/255.0    #normalising
print(data.shape)
data=np.reshape(data,(data.shape[0],img_size,img_size,1))
target=np.array(target)

from keras.utils import np_utils

new_target=np_utils.to_categorical(target)
print(new_target)


(981, 100, 100)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [4]:
new_target

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [7]:
np.save('data',data)
np.save('target',new_target)